#define TYPES

#define PACKET_SIZE 1400
#define PACKET_SPLIT 0xFFFFFFFE
#define PACKET_HEADER_LENGTH 4

#define A2S_CHALLENGE_LENGTH 4
#define A2S_CHALLENGE_CHAR 0x41
#define A2S_CHALLENGE_START (A2S_CHALLENGE_LENGTH + 1)